### ISSUE TITLE
Two sentences have text where lesson number should be

### ISSUE THREAD

**Issue by bast** [smartool/data-rus-eng#1]
Sentences 8609 and 9277. @lajanda 

This is not a big problem for me, I can work around that but something you might want to fix.

**Comment by lajanda** [comment]
Dear Radovan,
                I can’t see what the problem is. Sorry, I am a newbie to github and will have to learn my way around it.
                Maybe you can give me a description?
                --laura

**Comment by bast** [comment]
These two sentences:
```
SMARTool_data_B2_LIZA.csv:отказывать,8609,refuse,,A,B2,LM,2,отказывающем,Imperf.PresentActiveParticiple.Loc.Masc.Sing,"Дочь рассказала мне о своём отце, никогда не отказывающем ей ни в чём.","The daughter told me about her father, who never denied her anything.",,_,общение,Один пример в корпусе,

SMARTool_data_B2_LIZA.csv:помахать,9277,wave,,V,B2,LM,2,помахают,Perf.Plur.3,,,,_,_,НЕ нормативная форма. В словаре - помашут.,
```

If you carefully count the positions/commas you will see that at the position where there should be a lesson number (which can be empty, we do not expect all sentences to have a lesson number), you find some sentence or sentence fragment.

Again, this is not urgent, I just wanted to make sure this does not get forgotten.

**Comment by lajanda** [comment]
Aha. Sorry. This is a mistake of course. The information in the lesson column can just be deleted. And indeed any information that is not a lesson can be deleted.
                                --laura

**Comment by bast** [comment]
OK I will fix that.
