### ISSUE TITLE
Need to fix a tricky error

### ISSUE THREAD

**Issue by lajanda** [smartool/data-rus-eng#52]
There is an error in the B1_VALYA data, items 2942, 2943 and 2944.
The problem is that there are TWO verbs with the infinitive болеть. One verb means 'hurt' (that is the one that is illustrated in item 2942). The other verb means 'be ill' (illustrated in items 2943 and 2944). These are not just two meanings of the same verb because they have different conjugations in the present tense too. We need to split these two items so that they appear as two separate verbs: болеть 'hurt' vs. болеть 'be ill'. Is there a way to do this? I was not sure what to do.

**Comment by bast** [comment]
How about disambiguating the first csv column entries like this:
`болеть (hurting)` (in 2942)
`болеть (be ill)` (in 2943 and 2944)

**Comment by lajanda** [comment]
Thanks, Radovan! I have created a pull request with this change.

Laura A. Janda
Professor of Russian
UiT The Arctic University of Norway
https://uit.no/ansatte/person?p_document_id=41561
http://ansatte.uit.no/laura.janda/

________________________________

**Comment by bast** [comment]
Merged but I am not sure this will fix it. Let's see. If it doesn't then we either need to change first column of these lines or I need to change the code to not distinguish only based on the Russian word, but based on the Russian-English tuple.

**Comment by lajanda** [comment]
Dear Radovan,

This doesn't fix the problem. But I have an idea. I will make a change in the first column to distinguish the two. That way you don't need to change the code (which would be silly for just one verb). I will make another push request. 🙂

Laura A. Janda
Professor of Russian
UiT The Arctic University of Norway
https://uit.no/ansatte/person?p_document_id=41561
http://ansatte.uit.no/laura.janda/

________________________________

**Comment by bast** [comment]
Merged. Let's see whether this solved it.

**Comment by lajanda** [comment]
Perfect! Hooray!

Laura A. Janda
Professor of Russian
UiT The Arctic University of Norway
https://uit.no/ansatte/person?p_document_id=41561
http://ansatte.uit.no/laura.janda/

________________________________

**Comment by bast** [comment]
Perfect.
